const projects = [
  {
    title: "El Refugio",
    category: "interiores",
    discipline: "Diseño de interiores",
    image: "assets/img/el-refugio/cover.jpg",
    url: "proyectos/el-refugio.html",
    alt: "Proyecto de interiorismo El Refugio para el Casino de Madrid",
  },
  {
    title: "La Casa Encendida",
    category: "grafico",
    discipline: "Branding",
    image: "assets/img/la-casa-encendida/cover.jpg",
    url: "proyectos/la-casa-encendida.html",
    alt: "Rediseño de identidad visual modular para La Casa Encendida",
  },
  {
    title: "Let There Be Light!",
    category: "producto",
    discipline: "Diseño de producto sostenible",
    image: "assets/img/let-there-be-light/cover.jpg",
    url: "proyectos/let-there-be-light.html",
    alt: "Lámpara construida con envases plásticos reutilizados",
  },
  {
    title: "OCTOPUS Jeans",
    category: "grafico",
    discipline: "Branding",
    image: "assets/img/octopus-jeans/cover.jpg",
    url: "proyectos/octopus-jeans.html",
    alt: "Identidad visual para la marca OCTOPUS Jeans",
  },
  {
    title: "Torres Blancas",
    category: "interiores",
    discipline: "Diseño de interiores",
    image: "assets/img/torres-blancas/cover.jpg",
    url: "proyectos/torres-blancas.html",
    alt: "Proyecto de interiorismo Torres Blancas basado en el uso del color",
  },
  {
    title: "Coffee Party @ Ambu",
    category: "grafico",
    discipline: "Identidad efímera",
    image: "assets/img/coffee-party/cover.jpg",
    url: "proyectos/coffee-party.html",
    alt: "Identidad gráfica para el evento Coffee Party de Ambu",
  },
  {
    title: "Vintage Packaging",
    category: "grafico",
    discipline: "Packaging",
    image: "assets/img/vintage-packaging/cover.jpg",
    url: "proyectos/vintage-packaging.html",
    alt: "Packaging de champagne inspirado en la estética Art Déco",
  },
];
